<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_fw-input qa-password-field</name>
   <tag></tag>
   <elementGuidId>25ee7a24-a637-4030-a96a-dc0671895c53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.fw-input.qa-password-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93b9c0e1-2c8d-4c86-826e-3ea1d2b3e905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>NaN</value>
      <webElementGuid>9d357ee0-92da-4288-b995-c745dbc55abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>45554036-ad1e-49bc-a2be-07ff58b65dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>084586be-5ea6-46b3-8ef0-caa01500a629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-input qa-password-field</value>
      <webElementGuid>339e5bfd-ffd2-49db-94fd-5fa2f97b01eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;b-body-wrapper js-body-wrapper&quot;]/div[2]/div[4]/div[1]/div[@class=&quot;fw-popup__container h-width-100p fw-over-fixed-background b-auth-popup&quot;]/div[@class=&quot;fw-popup__body&quot;]/div[2]/div[2]/div[2]/div[@class=&quot;fw-field-container qa-fw-field-container b-auth-last-form-field&quot;]/div[@class=&quot;fw-field&quot;]/div[@class=&quot;fw-field__field-content&quot;]/div[@class=&quot;fw-field__content&quot;]/input[@class=&quot;fw-input qa-password-field&quot;]</value>
      <webElementGuid>aaa6068c-a4a9-47ef-8505-dd4d94ab48de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>bb30de09-5108-4d35-a662-e65149983ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div[4]/div/div/div/div[2]/div[2]/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>b224f424-4530-4c1d-b485-6fbcfabdb17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>d557d234-1392-443b-9945-e1ebf8894a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password']</value>
      <webElementGuid>9c1c0de4-7426-4cc6-8033-e9e840670dd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
