<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email or Phone_fw-input qa-login-field</name>
   <tag></tag>
   <elementGuidId>bd2b2bbd-4b21-4013-95e5-eadcf29280d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.fw-input.qa-login-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07f0f2af-596e-4b68-9531-43687101a177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>NaN</value>
      <webElementGuid>3bf49477-cb62-4892-997f-cefa3cd18dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>227256a4-0625-4cab-b5c4-5a3866116fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a1084c9d-b464-428a-a576-a9be7d58dae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-input qa-login-field</value>
      <webElementGuid>8dca8ae8-1503-4b73-a0c1-60a2fcf91298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;b-body-wrapper js-body-wrapper&quot;]/div[2]/div[4]/div[1]/div[@class=&quot;fw-popup__container h-width-100p fw-over-fixed-background b-auth-popup&quot;]/div[@class=&quot;fw-popup__body&quot;]/div[2]/div[2]/div[2]/div[@class=&quot;fw-field-container qa-fw-field-container&quot;]/div[@class=&quot;fw-field fw-focused&quot;]/div[@class=&quot;fw-field__field-content&quot;]/div[@class=&quot;fw-field__content&quot;]/input[@class=&quot;fw-input qa-login-field&quot;]</value>
      <webElementGuid>b45204ee-8e35-4801-990d-696df52e2879</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>61a537e2-7b4e-414f-b3e0-86eee3ad1717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div[4]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>f3355cfc-c6d3-490c-8608-8be8dfa0255b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>7ccd167c-4a7e-4df5-b6d0-2416aa023459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>9387c33e-1508-40ee-b468-87d16ace1c3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
