<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update Course</name>
   <tag></tag>
   <elementGuidId>b8b70a5c-b0e5-4993-ba47-bc2b55b8cf23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#update_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='update_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>425fdf69-7d63-4095-8074-34fb0c84f861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>update_btn</value>
      <webElementGuid>6b8bceb3-af34-4f0c-99b1-8fe5e019f677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>4452a31f-8eee-49f9-9d65-9d3667af0052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update Course</value>
      <webElementGuid>6a2b7aaf-744e-460d-9d8f-7702e04e27c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;update_btn&quot;)</value>
      <webElementGuid>504108dc-2ceb-4357-801f-c4b8ab4e2859</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='update_btn']</value>
      <webElementGuid>d4185e04-73fe-4507-8289-367e544f4063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[1]/following::button[1]</value>
      <webElementGuid>f7e506ad-acc4-420f-a7f5-8b4ae9051fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::button[1]</value>
      <webElementGuid>dad549de-5e60-444f-b8f6-67b230708761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Update Course']/parent::*</value>
      <webElementGuid>8750d013-0959-4b1f-83c3-43a83d5a8d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>6b0fa97a-498d-4af2-880e-ab41fb753a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'update_btn' and (text() = 'Update Course' or . = 'Update Course')]</value>
      <webElementGuid>2e0f6a4f-b87f-4a75-a3c3-cb827475f7ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
