<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign Up for Newsletter_assistance_all_2faa73</name>
   <tag></tag>
   <elementGuidId>36fa73d1-a725-4559-8813-4e2eb3833813</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#assistance_allowed_checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='assistance_allowed_checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c97b6a1e-7f07-4c2f-84c7-7cdaba6f8fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>822153db-c0b7-4281-8aa4-8b00fca62f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assistance_allowed_checkbox</value>
      <webElementGuid>befea8e2-0d8c-4ea2-937f-4ee01309d5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Allow remote shopping assistance</value>
      <webElementGuid>2092bb91-6d9d-4ae4-bc67-eeb0f2873dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2bc820f4-54fe-4c9b-8041-9383fef75bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>assistance_allowed_checkbox</value>
      <webElementGuid>4e0c27d4-268d-4c4c-8807-0e0cf1e915d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3561cc6b-afc4-4091-bb7f-f8cd39054cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assistance_allowed_checkbox&quot;)</value>
      <webElementGuid>d8448c4a-11f1-479d-bf8a-8ae4b3ab7b8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='assistance_allowed_checkbox']</value>
      <webElementGuid>d7d7e869-4404-4071-adc0-c70f52727a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-validate']/fieldset/div[4]/input</value>
      <webElementGuid>77b88542-b78a-4ab6-8c95-85a37af456f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>4d397287-a5f9-4322-81a1-804480642af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'assistance_allowed_checkbox' and @title = 'Allow remote shopping assistance' and @id = 'assistance_allowed_checkbox']</value>
      <webElementGuid>4cc65ab6-7e41-4785-a103-5c321fb97b6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
