<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Password_show-password</name>
   <tag></tag>
   <elementGuidId>7c2c9b21-2840-4743-85ad-5bcae7376aac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='show-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>371140da-69b0-46c3-887c-ce327a0602d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8c60d142-2472-4179-8a91-e1db96eb375e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>show-password</value>
      <webElementGuid>baa2bc61-a932-4e02-8039-ec88268ae695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {title : $t('Show Password')}, checked: isPasswordVisible</value>
      <webElementGuid>0b9aea75-c05a-47d8-8ecb-b384e4f54ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show-password</value>
      <webElementGuid>325663af-f8b6-4381-96a8-e0e4494b290c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b4c4b9a5-ce7a-40de-a31e-a36ed420c918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>show-password</value>
      <webElementGuid>c6584935-11bc-4022-8e77-d1209e62a0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Show Password</value>
      <webElementGuid>77263038-a6c0-442e-8878-0bdf5983c0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show-password&quot;)</value>
      <webElementGuid>3563fdf6-f104-448b-9f5f-a97d9b5a9740</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='show-password']</value>
      <webElementGuid>0d0422d3-185a-4f90-8862-41dc4021d603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-validate']/fieldset[2]/div[4]/input</value>
      <webElementGuid>f2704d1d-602b-431a-a44e-1b7c2648d081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div[4]/input</value>
      <webElementGuid>5b04068d-b5cf-4da5-88a6-4a4e9dddb937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'show-password' and @id = 'show-password' and @title = 'Show Password']</value>
      <webElementGuid>8a2affb7-03b9-43da-bb53-ad6cc9016bb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
