<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code_reg_no</name>
   <tag></tag>
   <elementGuidId>1770cd5f-7d49-45e4-92da-8f0de4426bc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reg_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reg_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3336290-8422-4b6a-80dd-805d09f03a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reg_no</value>
      <webElementGuid>d477f661-43a2-4258-9a46-080967a25907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reg_no</value>
      <webElementGuid>aaea7326-d130-4d54-a0f4-a14277fffc62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b322b4ee-bbc7-468e-ac36-40dbfe672854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>9f3e7c71-04d1-47b7-918d-0ccf22e44998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reg_no&quot;)</value>
      <webElementGuid>da072987-2552-4a78-8e16-62e6efbcaa4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reg_no']</value>
      <webElementGuid>a4b95db2-6bef-404c-92cc-c0ac6d58ab48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>5ca6e46f-3a70-430c-94e5-dda8127455a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reg_no' and @name = 'reg_no' and @type = 'text']</value>
      <webElementGuid>90ad01ae-1801-4ea0-a7ca-067a8cef10e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
