<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_show-password</name>
   <tag></tag>
   <elementGuidId>471d98ab-3e44-4c52-8c63-abc34addf9e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='show-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>201eb26a-2e34-468a-9832-57b79b3c7b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>26461715-a62a-442b-ab5b-d76217fbf068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>show-password</value>
      <webElementGuid>3a4f900b-fa6c-4c8a-ae45-34187fc2f450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {title : $t('Show Password')}, checked: isPasswordVisible</value>
      <webElementGuid>7a17af62-234b-4374-9081-36a78c1d48a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show-password</value>
      <webElementGuid>4bf875da-5c14-4cb8-8def-66b8052a8241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a2f34af6-e29d-48e1-9d5f-eb42b5eb38ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>show-password</value>
      <webElementGuid>7c224759-ccc8-4c38-8492-37b7fb9da58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Show Password</value>
      <webElementGuid>9cdb878b-3abd-4280-8485-0759375707a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show-password&quot;)</value>
      <webElementGuid>f498d579-f75c-42d1-ae10-c885b6dbdd8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='show-password']</value>
      <webElementGuid>35dda4d5-790e-4e92-8563-578bd104f4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/fieldset/div[4]/input</value>
      <webElementGuid>6b6f3d7f-f099-444b-9754-3377a616a256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>fffa2c62-11c8-41b6-bce1-e3bf9e687e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'show-password' and @id = 'show-password' and @title = 'Show Password']</value>
      <webElementGuid>ba0321f1-e719-4091-ac17-852829e9a51d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
