<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_M</name>
   <tag></tag>
   <elementGuidId>7c8d1583-71eb-4c36-91dc-cdde44922272</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.swatch-opt-694 > div.swatch-attribute.size > div.swatch-attribute-options.clearfix > #option-label-size-142-item-168</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='option-label-size-142-item-168'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8256020d-d974-4bd4-a30e-31d51a0da3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch-option text</value>
      <webElementGuid>a06c47d9-c727-4803-a3a7-5c9d2d428bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-label-size-142-item-168</value>
      <webElementGuid>2155aaa5-7bab-4c35-978a-980ef1be0d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1fe7b456-1c21-4fde-9531-21119aece5e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2a4ebc26-d6cf-4bae-b7fa-6272665d854a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>option-label-size-142</value>
      <webElementGuid>c68fb32e-5632-4cf2-a93b-fe7465103af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dfe59e5b-265d-4487-9c5b-848643b6babd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-type</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>28853059-c365-4919-a8c8-92b509196325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-id</name>
      <type>Main</type>
      <value>168</value>
      <webElementGuid>8a1389f5-6270-489c-bec5-81f3367f9b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-label</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>032bb14e-0326-4006-a631-01ce528fa1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>3395ee54-d681-4b01-abc0-cf1d0476ba50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>fafe59e4-d2cf-4b8e-b5ae-52fb564bb935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thumb-width</name>
      <type>Main</type>
      <value>110</value>
      <webElementGuid>c85a8725-1542-4423-bd4a-0ec266537c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thumb-height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>a08637bd-8547-415d-8c3f-8e0edd163251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-tooltip-value</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>5ff24980-1661-455d-8ec4-72fdf9d1d2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>cf215d22-10a2-45d7-88bc-b838b0147242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;widget block block-static-block&quot;]/div[@class=&quot;block widget block-products-list grid&quot;]/div[@class=&quot;block-content&quot;]/div[@class=&quot;products-grid grid&quot;]/ol[@class=&quot;product-items widget-product-grid&quot;]/li[@class=&quot;product-item&quot;]/div[@class=&quot;product-item-info&quot;]/div[@class=&quot;product-item-details&quot;]/div[@class=&quot;swatch-opt-694&quot;]/div[@class=&quot;swatch-attribute size&quot;]/div[@class=&quot;swatch-attribute-options clearfix&quot;]/div[@id=&quot;option-label-size-142-item-168&quot;]</value>
      <webElementGuid>4938f3ed-062e-4545-b6b2-650082eb2c73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='option-label-size-142-item-168'])[3]</value>
      <webElementGuid>acd90d19-3414-490b-b6ea-0cba4f69ecb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[3]/div/div[2]/div[3]/div/div/ol/li[3]/div/div/div[2]/div/div/div[3]</value>
      <webElementGuid>ac21afdc-f398-4b6b-91fb-91860a7bde59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[3]/following::div[1]</value>
      <webElementGuid>5d00ca12-2c7b-4dfd-b249-8885e54670bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XS'])[4]/following::div[2]</value>
      <webElementGuid>8e3b862d-4898-4a29-aae7-0364564b3606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='L'])[4]/preceding::div[1]</value>
      <webElementGuid>59bd8d41-9a33-4dfc-8cff-c44928558848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XL'])[3]/preceding::div[2]</value>
      <webElementGuid>73188742-8b0b-4f97-88fb-546e31ab153a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div[3]</value>
      <webElementGuid>48b6405c-1d0a-4141-919e-82c6cffae714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'option-label-size-142-item-168' and (text() = 'M' or . = 'M')]</value>
      <webElementGuid>89c7284a-88b1-4412-9c21-86ae09cf534d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
