<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_images_youtube-player-1</name>
   <tag></tag>
   <elementGuidId>c8ca8df3-66b5-4297-807e-d8963a2653c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#youtube-player-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='youtube-player-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2b233df5-a7fc-4996-b559-62cf3ae54492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>youtube-player-1</value>
      <webElementGuid>38ee405e-f35f-4727-9329-c19724ab7f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d21c179f-898e-4568-be78-b148c4ab345e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share</value>
      <webElementGuid>76ed5c7a-f293-4fbb-b6aa-cd62c79845e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>strict-origin-when-cross-origin</value>
      <webElementGuid>80fb9f92-ac33-469f-9f66-2c8c1c98cefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>2013 mercedes-benz sprinter Diesel</value>
      <webElementGuid>1b194637-e39a-42c4-8768-490cdd0f9bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>640</value>
      <webElementGuid>5e9bfa53-2ea2-4c2c-bf1c-862ff3a46c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>360</value>
      <webElementGuid>1670deee-1aa5-434e-a226-39ee5e918b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.youtube.com/embed/xCMWoRnX9ms?autoplay=0&amp;time=0&amp;enablejsapi=1&amp;origin=https%3A%2F%2Fjiji.ng&amp;widgetid=1</value>
      <webElementGuid>c6a4aca5-e4ca-42f1-a8d0-326d253cd5ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;youtube-player-1&quot;)</value>
      <webElementGuid>6a802e07-0991-4e42-b529-0c4d3b4980e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='youtube-player-1']</value>
      <webElementGuid>38d05c2a-d6fc-457a-855a-576b94eb661c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/div[2]/div/div/div/div[3]/div/div[2]/div/div/div[3]/div/div/div/iframe</value>
      <webElementGuid>6bf5d264-c647-44ba-843c-76bd619c084a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/iframe</value>
      <webElementGuid>9f30f024-ef5c-4ed4-8124-9e19d682bce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'youtube-player-1' and @title = '2013 mercedes-benz sprinter Diesel' and @src = 'https://www.youtube.com/embed/xCMWoRnX9ms?autoplay=0&amp;time=0&amp;enablejsapi=1&amp;origin=https%3A%2F%2Fjiji.ng&amp;widgetid=1']</value>
      <webElementGuid>a08f6120-0c79-481e-9fe9-9be0771042de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
