<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_Odunayo Balogun_video-stream html5-ma_c10ef7</name>
   <tag></tag>
   <elementGuidId>ed5a28b6-f07d-4d50-9ac5-1d9069111c71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>video.video-stream.html5-main-video</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='movie_player']/div/video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>32ff6bb5-9565-4295-8ae8-95c1d4a5e5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e27b9283-6ea3-4e46-9c1a-f549d8ab6852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>video-stream html5-main-video</value>
      <webElementGuid>e7d47e54-3a4d-47be-8fdc-6115ef1923bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controlslist</name>
      <type>Main</type>
      <value>nodownload</value>
      <webElementGuid>937af82f-14bf-4459-8b94-d892db76d0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:https://www.youtube.com/8a0c6dd3-d839-4259-a2e4-bdc0f9c2c8ca</value>
      <webElementGuid>acfc117d-7df8-45d4-8027-b421746ed85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;movie_player&quot;)/div[@class=&quot;html5-video-container&quot;]/video[@class=&quot;video-stream html5-main-video&quot;]</value>
      <webElementGuid>fa9802e4-f811-49c5-b2cc-a604b0545548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Jiji/Page_Mercedes-Benz Sprinter 2013 White in O_215eb8/iframe_images_youtube-player-1</value>
      <webElementGuid>60779578-2f94-4fab-9b85-dd1b47e9b0ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='movie_player']/div/video</value>
      <webElementGuid>f6e8b26f-a06e-467b-afb6-223633e4943d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>e67f1a6f-a42f-408e-9b49-ad1abb150661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@src = 'blob:https://www.youtube.com/8a0c6dd3-d839-4259-a2e4-bdc0f9c2c8ca']</value>
      <webElementGuid>a6e6d40c-5ed5-4fe1-944e-8bb03757a905</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
