<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code_reg_no</name>
   <tag></tag>
   <elementGuidId>578a62d7-da83-4070-bd79-769fc2d18bfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reg_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reg_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff4826e5-be60-416c-9bee-c24885314dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reg_no</value>
      <webElementGuid>12757d15-4e01-48ce-bf48-71bd5e890914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reg_no</value>
      <webElementGuid>4f7e9650-44b5-4cfd-9332-a2a4c23aee4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4c4be9bf-5cd2-4aff-9b37-3bdd8b369b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6625</value>
      <webElementGuid>87ac7abb-6fc6-4c23-b276-08f5c21aca07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>5135b0d8-c5ad-49d1-9d21-3a95a30bd5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reg_no&quot;)</value>
      <webElementGuid>5c971e8b-7d6c-4b34-8c7d-7e2b837266b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reg_no']</value>
      <webElementGuid>5831fece-9281-4d05-b093-228b4a52b775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>e2a5e751-c774-4649-bd78-124daad0e26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reg_no' and @name = 'reg_no' and @type = 'text']</value>
      <webElementGuid>a4f50c40-d7ff-4551-a021-30807343c7aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
