<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_show-password</name>
   <tag></tag>
   <elementGuidId>c07ce98a-c694-4fe7-be06-fc2a36e1765d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='show-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b5a99df-ea92-493f-aecb-e43a34a10f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c5106671-74dc-4bf0-aded-dd13c33608e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>show-password</value>
      <webElementGuid>284561c9-3bec-49b6-8d4f-c355f0837fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {title : $t('Show Password')}, checked: isPasswordVisible</value>
      <webElementGuid>dcf64184-db84-4110-a614-2666d56c4573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show-password</value>
      <webElementGuid>a93aed9f-c827-45e2-8d1a-e6c97ed3bab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>13f35047-447d-45ac-811e-fa69e1d6418d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>show-password</value>
      <webElementGuid>57dc51c0-a976-431a-808c-e88cd5086963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Show Password</value>
      <webElementGuid>96af196e-6aab-4d36-bbff-5c6f29344cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show-password&quot;)</value>
      <webElementGuid>09318f5b-7b76-46e6-8646-710b0f41f686</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='show-password']</value>
      <webElementGuid>7c0c9452-6a39-4b94-abc7-bd66c0703198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/fieldset/div[4]/input</value>
      <webElementGuid>f7aefeb9-7921-4e03-9eff-0806a2e3c34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>9127953b-dbc0-484d-ae91-82c118dc6208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'show-password' and @id = 'show-password' and @title = 'Show Password']</value>
      <webElementGuid>83117144-f606-4fe1-af6c-c1c4eaf846bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
