<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Delete</name>
   <tag></tag>
   <elementGuidId>3bb09da9-05fb-4f4d-a33f-15d6e001fd94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.list-group-item.d-flex.justify-content-between > div:nth-of-type(2) > a.btn.btn-sm.btn-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Delete')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>167194ce-8676-4624-b913-84897e50fc0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/student-courses/9/delete</value>
      <webElementGuid>ae1c0429-8aab-403b-a9c0-8c408c10303b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-danger</value>
      <webElementGuid>39387f90-e40f-4e7f-b360-05c11421105e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>e5940c61-c7a0-4bcc-9af9-38569943d553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-fluid mt-5&quot;]/div[@class=&quot;row d-flex justify-content-center&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;card mt-2&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;list-group&quot;]/div[@class=&quot;list-group-item d-flex justify-content-between&quot;]/div[2]/a[@class=&quot;btn btn-sm btn-danger&quot;]</value>
      <webElementGuid>b248d5e7-fa89-46ac-a663-f4065f3214c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Delete')])[2]</value>
      <webElementGuid>c5b0520a-f7f6-4cce-aa44-0c87b73a158d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mechanical Engineering Technology-002'])[1]/following::a[1]</value>
      <webElementGuid>0006e61b-4a6c-4676-b8fb-56375a5d112f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student Courses'])[1]/following::a[1]</value>
      <webElementGuid>e4a1e8a9-5b2e-4d52-89d3-b40d84d70e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mechanical Engineering Technology-002'])[2]/preceding::a[1]</value>
      <webElementGuid>e0e7325d-002b-43f5-924f-6a234b7fc0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[3]/preceding::a[1]</value>
      <webElementGuid>8aa64858-1619-49ed-bfa3-af4ad2599bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/student-courses/9/delete')]</value>
      <webElementGuid>52327e67-4ce0-419a-80fd-332f6d720019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/a</value>
      <webElementGuid>b532b946-ade1-446a-8a5a-473a1046383c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/student-courses/9/delete' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>b4b40ed6-162e-484f-b748-939cbecea45e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
