<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please type the letters and numbers b_cf1d96</name>
   <tag></tag>
   <elementGuidId>9a7def2b-527d-458e-89d6-729962a335c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#captcha_user_forgotpassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='captcha_user_forgotpassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e68c05d8-8c71-4ca5-8f34-2931616a909b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>captcha[user_forgotpassword]</value>
      <webElementGuid>1504186b-bc9a-4e1f-834d-2003df867ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fcba64f4-3c5c-46bd-8940-67f31db1f5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text required-entry</value>
      <webElementGuid>18b8a8ff-568d-4728-a8a7-d6b583ccfba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{required:true}</value>
      <webElementGuid>36139567-1a33-4b70-a119-775406dbb738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>captcha_user_forgotpassword</value>
      <webElementGuid>6db442ed-b720-4fd7-ae4b-a446c324a660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>492b3507-114a-4f07-9163-eb28bc21807e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c5d13ea0-b432-41fa-9ad2-fc4db0079d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;captcha_user_forgotpassword&quot;)</value>
      <webElementGuid>ef672c0d-9f28-4e37-87e9-da6cdb5a14c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='captcha_user_forgotpassword']</value>
      <webElementGuid>63ab7ab4-7d70-4344-aaea-ca190e71f848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-validate']/fieldset/div[3]/div/input</value>
      <webElementGuid>19c7b338-ad01-4fc5-8b38-cb194aca994b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[3]/div/input</value>
      <webElementGuid>ee814083-3bae-411b-ad2b-49ddf9c16908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'captcha[user_forgotpassword]' and @type = 'text' and @id = 'captcha_user_forgotpassword']</value>
      <webElementGuid>b9ef374b-cee0-4c2f-87c8-264dbb65a001</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
